language: ruby
rvm:
- 2.2.0
branches:
  only:
  - development
gemfile:
- Gemfile
before_script:
- psql -c 'create database ex_rails_test_db' -U postgres
- bundle exec rake db:create db:migrate db:schema:load
deploy:
  provider: heroku
  api_key:
    secure: ZCEE7Z5skz64y+N2HVObatKO1JC9Eyp4aOpBMCIr6WsTdf1lHzFtFvBB/39J9j0Asyssvxbe2Ba/oacJ67OW+QgVejh6ZZKkUsMQBB9DnOvl7+y3XJbKZv5vfGzBxi732CLRGOVeUwv0SghBTHyhDJlZtdQfG+KxG2hFNiA5ll4NRCB9Ix0dZ7Ur/DtS7D9WSwk+YPBkDGAZ2Bt8wu73/6Ma5kxVQzhqSxPJfNObDt+vomW05HrsCniUXGtyThNdrqVDg8iTp0otDlTfoz3PNxZ0S7BNimmtr1OYGEB77Cwx3hJekFCQbGPDBYIF0Uj+1yWbKTLu2P/4Wo6UfvQvvJz/aDM5UjR1/ccTIhLnaH+uIV5Tbv6uSLTZsQuwTdyuFlrnV7jiuePbtkkGOO9x180og4mJGXb5UB1Idf2bppdnrMH5nvd4h/YYgUqeVtJGtUjByZhVtPLQLpi/oXtn9akYQsXEWa+qyyin6NU1DY59B7aI3FE/o48+a8lza6olRpuSNcdo293oVMDS/o/COYjdEsEFjzKgDQq+u04QZ7NzfbWbKXwUItRS/V3kW2tQFAgIR9b+06JU8Qp/Sb44KokuDshlVU/CaUA7CELNESTjxY5N8PSWjfhMpmHKx+UzZkkJI8sY8jxg4brC7rVPVnzo4tCBZnOXvPzMq7E0TSM=
  app: book-store-1
  run:
  - rake db:migrate
  - rake db:seed
  - restart
  on:
    branch: development
    rvm: 2.2.0
